- src/templates/basic-page.js
- src/templates/program-page.js
This is to shrink the height of the header area when no hero image is present
> Add no-thumb class for missing hero images

- gatsby-config.js
As per advice from Gatsby Support, this is a test to see if removing gatsby-plugin-manifest from gatsby-config.js will resolve the 404 flash error on the index page.
> Remove gatsby-plugin-manifest to resolve 404 flash

- package-lock.json
- package.json
Implement [Properly set the pathPrefix and assetPrefix in the pluginData fix](https://github.com/gatsbyjs/gatsby/commits/gatsby-plugin-gatsby-cloud@3.2.1/packages/gatsby-plugin-gatsby-cloud)
> Upgrade Gatsby Cloud plugin

- gatsby-node.js
- package-lock.json
- package.json
- src/components/heroVideo.js
- src/components/mediaText.js
- src/components/video.js
- src/styles/heroVideo.css
- src/templates/program-page.js
- Feature branch URL: https://tqtest.gatsbyjs.io/
- New plugin: [react-player](https://github.com/cookpete/react-player)
- New component: [heroVideo.js](https://github.com/ccswbs/gus/pull/42/files#diff-b5e9d505fc92fc31d61e5165fd5a3e098139c5c687df4efc285e462a9c8b786a)
- New stylesheet: [heroVideo.css](https://github.com/ccswbs/gus/pull/42/files#diff-55017c62566ceca3c9bdb5f5c97bd3141a873461ab88094bb46c32e8803d91b3)
- Program page checks if Hero component is an image or video 
- Null checks for video width and height added to `gatsby-node.js`
- Multidev URL: https://herovid-chug.pantheonsite.io/
- Video width and height fields added to Remote Video media type
- Remote Video added as option for Program page feature area
- Improvements to Media views (filter by video url and tags)
- Removed …
> Add Hero video option for Program pages

- gatsby-node.js
To resolve `Field "nodeprogram" is not defined by type "mediaremote_videoRelationshipsFilterInput".` error
> Fix remote video relationships schema

- src/components/linksOuter.js
This is a fix for layout of links widget when the items are displayed in a list - was bunching up in first column of 12. Now takes up the full width of the space available.  
Also an AODA fix do not display a blank header (and paragraph) element when no data is entered. 
Note both of these are using the same drupal back end (https://api.liveugconthub.uoguelph.dev/
https://ugconthub.gtsb.io/chancellor (page as it is)
https://gusfixlist.gatsbyjs.io/chancellor (page as it is fixed)
does not affect pages that use a grid of images for the links widget:
Both of these pages are identical - with a heading for the links widget showing.
https://ugconthub.gtsb.io/welcome-home
https://gusfixlist.gatsbyjs.io/welcome-home
Only change was done to the linksOuter.js file (adding two null checks and one …
> fix layout for list

- src/components/mediaText.js
- src/components/video.js
- src/styles/heroVideo.css
- Add UG spinner code to `video.js`
- Fix playerID variable code in `mediaText.js`
- Override white background (introduced by UG spinner code) in `heroVideo.css`
1. Go to https://tqtest.gatsbyjs.io/spinner-test and confirm the grey background with yellow pulsing dot show up until the video loads
2. View source code of above page and confirm `<video>` element has a unique value for `id`
3. Go to https://tqtest.gatsbyjs.io/programs/bcomm-test and verify hero area has dark-grey patterned background
> Add UG spinner code and fix other video issues

- gatsby-node.js
- src/templates/sitemap-page.js
To create a page that links to all the Student Experience pages
FRONTEND (Gatsby): 
- sitempage-page.js - template page that filters the list of pages using a value passed in from gatsby-node.js 
- gatsby-node.js - added function that creates the listing page using specific values for student experience
BACKEND (Drupal): live
- no changes
TESTING: 
The page https://ugconthub-pagesitemap.gtsb.io/sitemap-se , should display all pages that have an alias that includes the keyword "studentexperience"
> Page sitemap

- gatsby-node.js
- package-lock.json
- src/components/widgets.js
- src/templates/basic-page.js
SUMMARY:
This feature will add an accordion widget to the widget field. This will allow for the addition of accordion elements to be added to a page. Each accordion can have as many expanding points as needed.  
BACKEND (Drupal): https://accordion-chug.pantheonsite.io/
- Paragraph Accordion Section 
- which only has one field that is a reference to the Accordion Block paragraph
- Paragraph Accordion Block
- Two fields, both of which are formatted so that basic html can be used 
-  Title
-  Text
FRONTEND (Gatsby): gus/accordion branch
- gatsby-node.js - add paragraph__accordion_section to widgetParagraphUnion
- widget.js - add code to display paragraph 
- basic-page.js - added to query to include the accordion paragraphs from drupal
TESTING (Gatsby Cloud): …
> accordian Widget configuration

- src/components/pageTabs.js
- src/templates/basic-page.js
This PR is to resolve FP 453934 opened by Student Experience. No backend changes were necessary.
- Add `drupal_id` to GraphQL tabs widget query in `basic-page.js`
- Use `drupal_id` for `tabID` in `pageTabs.js` to ensure each tab ID is unique
- Clean up and refactor `pageTabs.js` code
- Remove unneeded variables and stylesheet
Compare https://ugconthub-tabfix.gtsb.io/studentexperience/intlstudent/quarantine with https://www.uoguelph.ca/studentexperience/intlstudent/quarantine - on the live site, tab content fails to change because of duplicate tab IDs. On the PR build site, each tab should work properly
> Refactor tabs to fix duplicate ID bug (FP 453934)

- gatsby-node.js
- src/templates/basic-page.js
- src/templates/program-page.js
- Add the content type Custom Footer content to pages based on tags (units).
- both Basic Page and Custom Footer content needs to be tagged with a Units tag (one).
- modifed gatsby-node.js and basic-page.js to include 
- modified queries to add unit tag and to filter for custom footer based on the unit tag.
- added code in basic-page.js to display custom footer content if it exists.
- no changes
- in gatsby cloud - https://gusbasicfooter.gatsbyjs.io/
- page that has a footer - https://gusbasicfooter.gatsbyjs.io/alumni/ovc-alumni-association-awards
- page that does not have a footer - https://gusbasicfooter.gatsbyjs.io/studentexperience/off-campus-community-standards-protocol
- To add a custom footer
- add unit tag to taxonomy (note Ontario Veterinary College is the only one currently) 
- …
> Basicfooter

- gatsby-ssr.js
- src/components/shared/mediaText.js
- src/components/shared/sectionWidgets.js
- src/components/shared/video.js
Update external UoG scripts link and move UoG media player script call. Fixes bug where videos won't load unless a full page refresh occurs. The section widget component has also been refactored to allow for more versatile multi-column layouts.
- Update `gatsby-ssr.js` to:
- call new, refactored UoG scripts file
- include latest UG CSS file
- fix calls to Google font files so Roboto font loads correctly
- Update `video.js` to call `uog-media-player.js` directly
- Refactor `sectionWidgets.js` to use Bootstrap 5 classes and handle different media and text layouts
- General code cleanup
None.
- Go to https://www.gatsbyjs.com/dashboard/2e86c058-a370-4898-ae51-9698cd178e8d/sites/fc8e90a4-54ce-4012-a5fc-3302f05a3d6d/deploys
- Go to "Visit build" for the latest version of this PR build
- Visit …
> Update UG script and fix video

- gatsby-node.js
- src/components/shared/accordion.js
- src/components/shared/accordionWidget.js
- src/components/shared/generalText.js
- src/components/shared/sectionWidgets.js
- src/components/shared/widget.js
The Accordion widget has been refactored for compatibility with Bootstrap 5. Code for the Accordion and General Text widgets has been moved to separate component files. The title field for Accordion items in the backend has been changed from formatted text to plain.
- New widget files: `accordion.js` and `generalText.js`
- `sectionWidget.js` and `widget.js` modified to use the relevant component files
- Accordion widget code refactored for Bootstrap 5 compatibility as per https://getbootstrap.com/docs/5.0/components/accordion/
- Schema in `gatsby-node.js` updated to use new Accordion title field
- New title field created for accordion items (using plain text instead for formatted, thus reducing complexity and the possibility of conflicts with Bootstrap 5 classes)
- New `Stay Open` boolean …
> Refactor Accordion widget for Bootstrap 5

- src/components/shared/stats.js
Added text-break class to prevent text from overflowing the cards in the Stats widget
Added text-break class to prevent text from overflowing the cards in the Stats widget
n/a
https://build-13c113d6-8cf5-41fa-a29a-9d74d5a68d7f.gtsb.io/
1. Go to /about and /choose-u-of-g and verify that the text in the Stats widget doesn't go beyond the card boundaries when resizing the browser window
> add class to prevent text overflow in the card

- src/templates/program-page.js
Remove the dark grey Call to Action area from the top of the program page template
- Code to render the top Call to Action area deleted from `program-page.js`
N/A
Go to https://www.gatsbyjs.com/dashboard/2e86c058-a370-4898-ae51-9698cd178e8d/sites/fc8e90a4-54ce-4012-a5fc-3302f05a3d6d/deploys and, once the Pull Request build has finished, open it and review the program pages to ensure the dark grey area is gone and no unintended consequences have occurred as a result.
> Remove Call to Action area from top of page

- src/templates/program-page.js
Refactor the code on the program page to take the program information and display it as an accordion instead of tabs.
Removed the tabs section for program information.
Added accordion - checks to see if content exists. If at least one item is there - display the Program Information header and the accordion for the appropriate section(s).
https://gusprogaccordion.gatsbyjs.io/
none
https://gusprogaccordion.gatsbyjs.io/programs/bachelor-of-arts-general-fully-online - has all four items.
https://gusprogaccordion.gatsbyjs.io/programs/master-of-dairy-technology-management has no items (nothing is displayed)
https://gusprogaccordion.gatsbyjs.io/programs/master-of-planning has just one (Selected Courses)
https://gusprogaccordion.gatsbyjs.io/programs/master-of-data-science has two items Selected …
> Progaccordion

- gatsby-node.js
- src/components/shared/blockWidget.js
- src/components/shared/sectionWidgets.js
- src/components/shared/widget.js
- src/templates/program-page.js
Make widgets available to the Program content type to offer more flexible layout options and add new widget for including custom blocks
- Widget component called in `program-page.js`
- `sectionWidgets.js` refactored to use section classes for differing column widths
- New component `blockWidget.js` for rendering the text of a Drupal custom block
- `gatsby-node.js` updated to include required schema for changes above
- Add widgets to Program content type
- Add Block Widget paragraph type
- Enable block-related jsonapi
Gatsby Cloud site: https://tqtest.gtsb.io/
Drupal multidev: https://progwidgets-chug.pantheonsite.io/
- Go to https://tqtest.gtsb.io/programs/bachelor-of-arts-and-sciences and verify it has a similar layout to the mockup at …
> Add widgets to Program content type

- src/components/shared/widget.js
Improved spacing between section widgets
Change `mt-5` to `mb-5` in `widgets.js` 
N/A
Once the PR build is complete on Gatsby Cloud, make sure pages that use sections still have proper spacing in wide and narrow viewports
> Space sections with margin-bottom instead of top

- src/components/shared/breadcrumbs.js
- src/components/shared/sectionWidgets.js
Remove home link functionality and unnecessary title.
This is just a temporary fix until we can confirm that the other fix works.
List all significant changes to the Drupal site (e.g. new fields, content types, modules, etc)
Insert steps. Include URLs of Gatsby Cloud test site and Drupal multidev.
> Remove home link functionality and unnecessary title (Temp Fix)

- src/components/blocks/economic-impact/national-impact-stats.js
- src/components/blocks/international/international-explore-grid.js
- src/components/blocks/international/international-explore-lead.js
- src/components/blocks/international/international-stats-global.js
- src/components/blocks/international/international-talk-current-student.js
- src/components/blocks/international/international-things-to-know.js
- src/components/shared/mediaText.js
- src/components/shared/statistic.js
- src/data/block/international/international-explore-lead.yml
- src/data/block/international/international-explore-things-to-know.yml
- src/data/block/international/international-stats-global-impact.yml
- src/data/block/international/international-talk-current-student.yml
- Updates for International
- Put stats in PageContainer (instead of full width)
- Add PageContainer to any international components that are not full width (instead of placing them in the section widget which affects the spacing by adding too many nested rows)
- Add aria-hidden to icons
- Align text beside icons so longer titles do not wrap under the icon
- Update structure of definition lists for accessibility
- Update colour contrast for accessibility (blue links on Explore U of G section)
- Update margins on talk to a current student section
- N/A
- ~Visit https://build-9ccd564b-6b69-461a-b651-13c29e057d2d.gtsb.io/explore-university-of-guelph-international~
- Updated Build: https://build-9784f134-ed45-4388-a076-5f7e8dfc87a4.gtsb.io/explore-university-of-guelph-international
> Updates for International

- src/components/blocks/economic-impact/anchors.js
- src/components/blocks/economic-impact/community-impact-campus-stats.js
- src/components/blocks/economic-impact/community-impact.js
- src/components/blocks/economic-impact/human-impact-stats.js
- src/components/blocks/economic-impact/intro-stats.js
- src/components/blocks/economic-impact/national-impact-stats.js
- src/components/blocks/economic-impact/pres-message.js
- src/components/blocks/economic-impact/provincial-impact-stats.js
- src/components/blocks/international/international-explore-lead.js
- src/components/shared/pageContainer.js
- src/components/shared/statistic.js
After updating International statistics for accessibility, I'm updating Impact Report to fix the same accessibility issues (colour contrast, definition lists). The same stat style is being used on the Lang template, so I fixed it here (on a page that's already live) in preparation to fix it on Lang:
- Ensure definition lists only contain a single div (containing dt and dd elements) instead of two nested divs
- **The issue:** Once I removed all the extra column wrapper divs, the bordered statistics no longer had a gutter between them (a.k.a the extra column wrapper div was necessary to contain the entire bordered card within the boundary of a column).
- **Solution:** Added a Statistic.Grid component that uses CSS Grid instead of Bootstrap row-cols-* classes. This allows us to use gap-4 …
> A11y fixes on Impact Report (DL and colour contrast)

- src/components/blocks/economic-impact/community-impact-mealcare.js
- src/components/blocks/economic-impact/human-impact-banky.js
- src/components/blocks/economic-impact/provincial-impact-intro.js
- src/components/shared/modalVideo.js
- src/components/shared/overlay.js
- src/components/shared/widget.js
Resolves the bug where videos would keep playing even if modal dialog was closed by using react-player and react-bootstrap components
- Refactor `modalVideo.js` to use `react-player` instead of `video.js` 
- Use `Modal` and `CloseButton` components from `react-bootstrap`
- Add event handlers to modal and close button to stop video playback
- Add `onClick` handler to modal button to both open modal and start video playback
- Use `modalVideo.js` component in `overlay.js`
N/A
- Go to https://previewugconthub.uoguelph.dev/programs/bachelor-of-indigenous-environmental-science-and-practice
- Click play button
- Verify modal opens and video playback begins automatically
- Verify playback stops if you hit `Esc`
- Verify playback stops if you click away from the modal
- Verify playback stops if …
> Fix modal video on Program pages

- src/components/blocks/international/international-things-to-know.js
A fourth 'thing to know' has been added to the 'Things You Should Know About the City of Guelph' section of the 'International: Study in Canada' page:
https://www.uoguelph.ca/study-in-canada-improve-life
The change requested is for 2 rows of 2 items max.
Bootstrap class has been modified in `blocks/international/international things-to-know.js`.
Logic has been added to hide buttons if `nolink` is used in Drupal YAML block
Drupal YAML block 'international_explore_things_to_know' has been modified to add 4th item. Where no link is available `nolink` is used for link child items (i.e. Title and Url).
- go to the test page (https://dwletsgo94170.gtsb.io/study-in-canada-improve-life) and verify that 'Things You Should Know About the City of Guelph' section shows the 4 items in a 2 row by 2 …
> Study in canada

- gatsby-node.js
- src/components/shared/sectionWidgets.js
- src/components/shared/statistic.js
- src/components/shared/statisticWidget.js
- src/components/shared/story.js
- src/components/shared/widget.js
- Add new statistics module.
- Add 4 statistics styles: Left Border, Gradient of Solid Colours, Solid Colours, and Light Blue
- Allow StatIcon to pick up the colour from the statistics style
- Add Statistics Item paragraph type (contains content for each statistic)
- Add Statistics Widget (New) paragraph type to contain Statistics Items
- Make Statistics Widget available on Basic Page in the Widgets, Section and Story paragraph types
- Add taxonomy type Statistics Styles to hold the available stat styles
**Multidev:** http://storystat-chug.pantheonsite.io
1. View the page at https://storystat-chug.pantheonsite.io/node/972/edit?destination=/admin/content for an example of statistics in use
2. Create your own statistics example if you wish
3. Check the paragraph permissions
4. Review the …
> Add Statistics (New) widget

- src/components/shared/sectionWidgets.js
Add margin bottom to primary section when secondary appears below in narrow view
**Before change:**
**After change:**
Add margin bottom to primary section when secondary appears below in narrow view
None
1. Visit the MM Test build: [https://mmtest.gatsbyjs.io/](https://mmtest.gatsbyjs.io/)
1. View any pages with both primary and secondary sections (e.g. https://mmtest.gatsbyjs.io/lang/commerce/global-leader)
2. In a wider viewport, confirm that there is no margin below the primary section when larger than medium size.
3. In a narrow viewport, confirm that when the secondary section moves below the primary section, there is now padding.
> Add margin bottom to primary section when secondary appears below in narrow view

- .github/workflows/azure-static-web-apps-yellow-water-03b355f0f.yml
- azure-pipelines.yml
Switch pipeline triggers to main.
- If Azure pipelines are being used, triggers should work against the main branch instead of the master branch.
None
Pipelines are not currently used but the change should have no adverse effect on our existing build.
> Switch triggers from master to main

- src/components/shared/headerMenu.js
Added a condition to not render the first item in a dropdown menu, if it has been set to `<nolink> or <button>`
in Drupal.
Added acknowledgement and condition to headerMenu.js 
Menus will need to modified to add `<nolink> or <button>` option as necessary, to avoid duplicate menu items.
- Uses the https://profiles-chug.pantheonsite.io/ multidev
- Menu https://profiles-chug.pantheonsite.io/admin/structure/menu/manage/president-s-office-main has been modified to have one `<nolink>` item, and one `<button>` item
- Check https://build-e754e286-3c11-42e6-938e-2d3fe9000339.gtsb.io/president - Our Team and Initiatives should not have a duplicate item. Awards & Scholarships has a duplicate since it uses a regular link.
- https://build-e754e286-3c11-42e6-938e-2d3fe9000339.gtsb.io/studentexperience …
> Add check for empty url in menu item

- src/components/shared/testimonial.js
Updated testimonial slider so it shows "Associated Profile" as the link title if none is provided for the Testimonial profile link.
Before fixing
After fixing
Updated testimonial slider so it shows "Associated Profile" as the link title if none is provided for the Testimonial profile link.
None
You can use the following multidev for testing: http://fixtestimon-chug.pantheonsite.io
On that multidev, I've updated the testimonial for Emil Kovacevic so the profile has a URL, but no link text. It should show "Associated Profile" on the /widget-examples page (scroll to the bottom): https://build-ac2aa3f6-2f2f-40d1-943c-844eaf9a84e4.gatsbyjs.io/widget-examples
> Add fallback if no testimonial profile link title

- src/components/shared/button.js
Ensure Call to Action is centred, while leaving other button types unaffected.
- Call to Action buttons should be centred in the narrow view
- Other buttons should be unaffected
- None
- Run the branch using data from api.live
- Check /university-of-guelph and confirm the call to action button at the bottom has centred text in the narrow view
- Check other pages with buttons (e.g. future-students) and confirm that buttons appear as expected
> Centre CTA buttons in narrow view

- src/data/block/home/home-accordion.yml
- src/pages/index.js
- Update Content Hub index page (see FP # 502985)
- Update page metadata
- Update page content
- Add Accordion for page content (data coming from yaml file)
None
- See https://mmtest.gatsbyjs.io for changes or run locally
> Index update

- src/components/blocks/canada/south-asia-explore-grid.js
- src/components/shared/yamlWidget.js
Add South Asia yamlblock front-end code
Add South Asia yamlblock front-end code (basing it on international-explore-grid
None
- Check the page /canada and ensure yamlblock is showing
> Add South Asia Explore Grid yamlblock

- src/components/blocks/economic-impact/national-impact-story.js
- src/components/blocks/economic-impact/provincial-impact-onehealth.js
- src/components/shared/mediaText.js
- src/components/shared/storyImageCutout.js
- src/components/shared/widget.js
- src/components/shared/yamlWidget.js
- src/styles/global.css
- src/utils/ug-utils.js
Rebuild the Economic Impact Report as a basic page using widgets so it no longer needs to be hard-coded within this repository
- add new yaml components `national-impact-story.js` and `provincial-impact-onehealth.js`
- reference new components in `yamlWidget.js` and remove unused ones 
- fix `gatsbyImage` width in `mediaText.js` and `storyImageCutout.js` so images are resized correctly
- add `slugify` function to `ug-utils.js`
- add `id` to `Section Title` to enable use of anchor links
- add new rules to `global.css` to address formatting requirements not provided by default Bootstrap classes
- add new text format `Hardcore HTML` to override CKeditor limitations (e.g. automatic removal of empty `<i>` tags) and limit its use to the Administrator role
- add `economic_impact_national_story` …
> Rebuild Economic Impact Report with widgets

- src/components/shared/headerMenu.js
- src/components/shared/navTabContent.js
- src/utils/ug-utils.js
Fix bug that results in a failed build when a disabled Drupal menu item has one or more enabled children.
- Add check for undefined and disabled parent in `headerMenu.js`
- Remove unnecessary escape characters in `ug-utils.js` version of `slugify` function (fixes eslint warning)
- Remove unused variable and import from `navTabContent.js` (fixes eslint warning)
N/A
- Go to https://langmenu-chug.pantheonsite.io/
- Create or modify a menu so it has a disabled top-level link with one or more enabled child links
- Run a build on https://www.gatsbyjs.com/dashboard/2e86c058-a370-4898-ae51-9698cd178e8d/sites/e1480ab1-9d0f-4dcb-9fda-75347c74c1c9/deploys (or test locally)
- Verify the build completes successfully with no errors
> Fix disabled parent menu link bug

- src/components/shared/testimonial.js
Removed duplicate id on testimonial slider (it has a main-column ID which already appears on the main container column).
- Removed duplicate id on testimonial slider (it has a main-column ID which already appears on the main container column).
None
Check any page with a testimonial slider using Siteimprove (e.g. Strategic Plan). Prior to the fix, you'll see a duplicate ID Level A error. After the fix, the error will have disappeared.
Fixed version: https://build-7aea34b3-c6f4-4745-b805-1fe4af13125c.gatsbyjs.io/strategic-plan/
> Remove duplicate id on testimonial slider

- src/components/shared/sectionWidgets.js
If only media and text widgets exist in the Primary region of a a section, automatically create a grid from the contents.
Grid is stacked at XS, 2 columns at SM, and either 3 or 4 columns at LG (depending on number of items).
This fixes the responsiveness of pages like:
https://www.uoguelph.ca/study-in-canada/
https://www.uoguelph.ca/studentexperience/off-campus-living/
Note that on...
https://preview-ugconthub.gatsbyjs.io/lang/about-ug-lang/
The user would have to remove the general text widget from the section and instead use the section title field. At that point, the grid will kick in because the section only contains media + text widgets.
If only media and text widgets exist in the Primary region of a a section, automatically create a grid from the contents.
None
1. Run locally or …
> Automatically create responsive grid for sections containing only media/text widgets

- .gitignore
- src/components/shared/linksElement.js
This was a request from Linda, she wanted the heading in the links element to have centered text and less spacing between the image and heading
- Added two classes to HeadingElement in linksElement.js
N/A
1. Go to https://ugconthub-linksspacing.gatsbyjs.io/healthy-campus and view the links element at the top of the page
1. Ensure the heading is centered and spaced correctly
1. Do the same for other pages that use the link element:
https://ugconthub-linksspacing.gatsbyjs.io/studentexperience
https://ugconthub-linksspacing.gatsbyjs.io/explore-all-programs
> Update spacing and center text in Links Element

- src/pages/404.js
- src/styles/global.css
- Add 404 page to Content Hub
- Update footer so it sticks to the bottom of the page
- Add 404 page to Content Hub
- none
Go to /jfkdlsjkla and when Gatsby shows there's no such page, select "Preview custom 404 page" button to see the page.
> Add 404 page to Content Hub

- src/components/shared/sectionWidgets.js
Update media grid logic so it allows for single image.
Fixes the issue where a single image in a Media Text widget in a primary region does not take up the full space. See the map on https://www.uoguelph.ca/grce/impact-report/ for an example.
Update media grid logic to only apply the grid logic if there's more than one image.
None
1. Check the deployed environment and confirm that the map is fixed: /grce/impact-report/
2. Confirm that the grid still responds as expected on /studentexperience
**NOTE:** You can ignore the missing styles from the styled-components. Styles are normally loaded from https://cdn.uoguelph.ca (which is basically another domain for our Azure production URL) however the style file that is generated does not live on our production server yet, so it won't be able to …
> Update media grid logic so it allows for single image

- src/components/shared/breadcrumbs.js
Linda asked me to make some changes to the breadcrumb styles, since most of those styles live in UofG-styles-dist.css, I've already made those changes seperately. All that remains on the Gatsby side is the home icon styles
- Added "fa-sharp fa-light" classes to icon in breadcrumb.js
N/A
1. View any page with breadcrumbs on it (ex. /president/presidential-installation/)
1. Ensure the home icon style looks like this https://fontawesome.com/icons/house?f=sharp&s=light
> Update home icon style in breadcrumbs

- gatsby-node.js
- src/components/shared/sectionWidgets.js
- src/components/shared/widget.js
Added an option in the Section Widget to change the heading level that will be displayed for the section title. Defaults to h2 if no choice is selected, and otherwise allows for headings to be used from h2-h6. 
gatsby-node.js
- added field_heading_level to the schema for paragraph__section type
sectionWidgets.js
- added field_heading_level to the query for paragraph__section type
widget.js
- added a variable to HeadingLevelSec that checks for and uses the heading level that was selected (defaults to h2 if none is selected) 
- Removed the line of code that defaulted the heading to h2 and replaced with a similar line that instead uses HeadingLevelSec to set the heading level of the section title
Multidev: [https://secheading-chug.pantheonsite.io/](https://secheading-chug.pantheonsite.io/) …
> Addheading

- src/components/shared/mediaText.js
Add id to media text headings so users can link to a media heading as part of their anchor links.
Add id to media text headings so users can link to a media heading as part of their anchor links.
None
1. Check a media and text widget
2. See if there is an id on it
> Add id to media text headings

- gatsby-config.js
Increase timeout to 60000 for wordpress query
None
None
See if build completes
> Increase timeout to 60000 for wordpress query

- src/components/shared/heroVideo.js
- src/components/shared/mediaText.js
- src/utils/ug-utils.js
Fix issue where video URLs show "Video Unavailable" when we add YouTube videos.
Patterns that should work are...
- https://youtu.be/YIFSRE8SjtM?si=ARa347KgObNy3lAa. 
- https://www.youtube.com/watch?v=YIFSRE8SjtM
- https://youtu.be/Lj2O9OkBr3Q
Fix issue where video URLs show "Video Unavailable" when we add YouTube videos
[x] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users:
- On [Media page](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup/SitePages/Media. …
> Allow new YouTube embed URL pattern

- src/components/shared/courses.js
Update Notes logic and heading margin
- Update Notes logic to display notes in 12 columns when there is no course data (it was supposed to do this before, but it was not checking to see if the array was empty, only if the array was undefined or null)
- Update Notes heading (h4) to have a top margin of mt-2
[Not applicable] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
**Before:**
**After:**
**Before:**
**After:**
None
1. Open the Gatsby Cloud or Netlify build: …
> Update Notes logic and heading margin

- gatsby-node.js
- src/components/shared/mediaText.js
Summary of changes
Note: this replaces PR #153 - will leave it for comments 
Added an option in Media Text Widget to display images on the right of the text block. Left the default (or no choice) to the image displayed on the left.
Frontend
gatsby-node.js
added field_media_alignment to schema for paragraph__media_text type
mediaText.js
added field_media_alignment to the query.
added code to check if field_media_alignment  data exists (default to 'Left' if does not) and assign it to a variable.
refactored code to check what side the image is to appear on and to render it either on the left or right. Alignment choice will if media and text are not in a row.
Backend
Multidev: https://imagealign-chug.pantheonsite.io/
In the Paragraph type: Media and Text added the field Media Alignment - …
> Media Alignment for text and media on the same row

- src/components/blocks/ovc/footerSocial.js
Change the footer icon for twitter from the bird to the X. In the OVC custom footer. 
in srs/components/blocks/ovc/footerSocial.js removed the old twitter icon import and added FaSquareXTwitter import from fa6 react Icons
[X] My changes are accessible (at minimum WCAG 2.0 Level AA)
[X] My changes are responsive and appear as expected on mobile and desktop views.
[N/A] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
No changes 
Build locally - with the live site backend (https://api.liveugconthub.uoguelph.dev/) check any OVC page for the new X twitter logo in the footer …
> change twitter icon to xtwitter icon

- src/components/shared/linksElement.js
- src/pages/404.js
Set heading on links widget to appear as an h4
Set heading on links widget to appear as an h4
Broken
Fixed
None
- View https://deploy-preview-183--ugconthub.netlify.app/explore-all-programs/
- Confirm the headings appear as h4s instead of h2s
> Set heading class to h4 for linkswidget grid

- azure-pipelines.yml
Azure DevOps [recommends](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1?view=azure-pipelines) switching from the [PublishBuildArtifacts@1](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1?view=azure-pipelines) task to the [PublishPipelineArtifact@1](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-pipeline-artifact-v1?view=azure-pipelines) for faster performance.
None
None
1. Run pipeline (since it's a PR affecting the pipeline, it will take an hour, so I ran it over lunch): https://dev.azure.com/uoguelph/CCS/_build/results?buildId=16513&view=results
2. Confirm nothing has changed in how the artifact is created on the pipeline (you should see 1 published …
> Use the PublishPipelineArtifact task (as recommended by Azure DevOps) on pipeline

- src/components/shared/pageTabs.js
- src/styles/pageTabs.css
Added the ability to link to a page and have a specified tab open.
- Refactored pageTabs.js to use react-bootstrap
- Add link logic to pageTabs.js
- Added pageTabs.css to fix styles for react-bootstrap version of tabs
N/A
Insert steps. Include URLs of Netlify test site and Drupal multidev.
1. Go to any page using the tabs widget (ex. https://deploy-preview-190--ugconthub.netlify.app/admission/undergraduate/requirements/canadian-t …
> Add ability to link to tabs

- .prettierrc
- src/styles/hero.css
Fixes the issue with the hero image being cutoff on the top and bottom on ultra wide displays the same way as on doorknob.
N/A
https://deploy-preview-194--ugconthub.netlify.app/
1. Go on any page with a hero image ex. https://deploy-preview-194--ugconthub.netlify.app/international/undergraduate-faqs/
2. Test the page at various breakpoints: mobile, desktop, laptop, ultra wide, etc.
3. …
> Ultrawide Hero

- package.json
Set gastby-adapter-entlify to ^1.0.4
I'm noticing build is behaving differently on preview. When the cache is fully cleared, it works, but then the next build it does not show the change.
Review if build works as expected.
> Set gatsby-adapter-netlify to ^1.0.4

- gatsby-ssr.js
Rather than having the version for the web components nom package hardcoded, I changed it so it is using a env variable. This will allow us to set the env variable on Netlify (which I have already done) so that we can have the preview builds use beta versions of the npm package.
- updated gatsby-ssr.js to use env variable instead of hardcoded url
N/A
- Test that the changes to the top nav are appearing (see …
> using env variable for web component cdn url

- package-lock.json
- package.json
Hotfix for issue where testimonial sliders with a single testimonial shows 3 duplicates in a column.
Downgrade `react-slick` to v0.29.0
Go to https://deploy-preview-207--ugconthub.netlify.app/engineering/undergraduate/future-students/computer/ and https://deploy-preview-207--ugconthub.netlify.app/programs/bachelor-of-engineering/ and verify the testimonial displays properly.
> Downgrade react-slick to resolve single testimonial bug

- src/components/shared/headerMenu.js
- src/templates/page.js
Allow pages associated with disabled menu links to show their menus
Allow pages associated with disabled menu links to show their menus
None
1. Ensure sample page /president/sustainability shows its menu.
> Allow pages associated with disabled menu links to show their menus

- src/components/shared/mediaText.js
The original default of the media and text widget was an h3, so we are reverting back to that default.
Set default of media and text widget heading to h3
None
1. Review the deployment and see if wide-spread issues with nested headings are fixed.
2. Review pages like https://deploy-preview-210--ugconthub.netlify.app/healthy-campus/
> Set default of media and text widget heading to h3

- .gitignore
- backstop.config.js
- backstop.json
- config/backstop/README.md
- config/backstop/default.js
- config/backstop/sample-config.js
- config/backstop/uofg-footer.js
- config/backstop/uofg-header.js
- package-lock.json
- package.json
- Add backstopJS for visual regression testing
- Add default configuration that tests three pages (basic page, explore our programs, program page)
- I've hidden all gatsby images on this one for the time being to avoid failures due to image differences
- Add uofg-header configuration (only tests header component)
- Add uofg-footer configuration (only tests header component)
- Styled components have flaky behaviour (sometimes they load, sometimes they don't by the time the screenshot is taken).
- Testing requires users to set two environment variables (url for testing and your reference url). It also requires people to run the test scripts themselves (i.e., See Test Plan below)
None - changes exist on front-end code but are meant to facilitate testing
[x] My changes are accessible (at …
> Add BackstopJS for visual regression testing

- src/styles/breadcrumbs.css
Override of CCS for Breadcrubs to not shorten page name. I.E. max-width: none;
Added !important to breadcrumbs.css file to add max-with: none !important; for element
changed breadcrumbs.js to include breadcrubs.css file
Reason for second PR - in testing did not need !important for local builds. But after PR#206 was merged, the new CSS was over taken by the existing. Thus, using !important 
Note: This is the first step on the breadcrumb fixt to not shorten the page names. This will aggravate the too log of list of breadcrumb issue.  Next step is to confirm with design team on how to handle too long of a list (scroll or Home/.../pagename. 
[?] My changes are accessible (at minimum WCAG 2.0 Level AA)
[ ] My changes are responsive and appear as expected on mobile and desktop views.
[ NA] …
> add !important to breadcrumbs.css

- gatsby-ssr.js
Changing the CDN we use to load the web components from unpkg to jsdelivr. Also added the ability to change the CDN using an env variable.
See https://github.com/ccswbs/doorknob/pull/53 for more info
Updated gatsby-ssr.js to point to jsdelivr instead of unpkg
[ X ] My changes are accessible (at minimum WCAG 2.0 Level AA)
[ X ] My changes are responsive and appear as expected on mobile and desktop views.
N/A
1. Go to the preview url
2. Ensure the header and footer load on the page
> Change from unpkg to jsdelivr and use env variable for CDN base URL

- src/components/shared/imageOverlay.js
- src/components/shared/storyImageCutout.js
Entropy is not supported by Netlify Image CDN. Replacing the focus with CENTER instead.
Swapped Story Image and Image Overlay widgets to use CENTER focus instead of ENTROPY.
None.
1. Ensure image shows on image overlay at /research/innovation
2. Ensure image shows in story image at /lang/commerce/expertise
> Fix blurred images on Story Image and Image Overlay

- src/components/shared/pageTabs.js
warning  React Hook useEffect has a missing dependency: 'tabs'. Either include it or remove the dependency array react-hooks/exhaustive-deps
Memoizes Tabs using useMemo. 
Reference: https://kinsta.com/knowledgebase/react-hook-useeffect-has-a-missing-dependency/ 
const tabs = useMemo(() => {
return props.pageData?.relationships?.field_tabs ?? []
}, [props.pageData?.relationships?.field_tabs])
}, [tabs])
[ x] My changes are accessible (at minimum WCAG 2.0 Level AA)
[ x] My changes are responsive and appear as expected on mobile and desktop views.
[ x] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my …
> PBI #76851 Fix warning  React Hook useEffect has a missing dependency

- src/components/layout.js
Add uofg-back-to-top as part of the default layout. See https://github.com/ccswbs/web-components/pull/20 for the code.
- Modified layout.js to add the back to top button
N/A
1. Go to any site that is scrollable.
2. Scroll down the page
3. Ensure the back to top button appears in the bottom right of the screen
4. Click the button
5. Ensure the page is scrolled back to the top of the page.
> add back-to-top button

- src/components/shared/mediaText.js
The changes are made to the description part of the media and text widget for videos to be aligned from the bottom.
Made changes to the default and large mediaSize for video descriptions and buttons to include textColHeight = "h-100";.
[X] My changes are accessible (at minimum WCAG 2.0 Level AA)
[X] My changes are responsive and appear as expected on mobile and desktop views.
[N/A] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
Check this link to make sure the changes are correct: https://deploy-preview-238--ugconthub.netlify.app/admission/undergraduate/campus/. Check other examples of media & text widget and confirm …
> fixed the media description to have consistent layout

- src/templates/page.js
Add Condition in Primary navigation for No Menu (no-menu machine-name) that will force a page to have no menu displayed even if it gets put into a menu.
Modified file page.js to have a condition for the no-menu in primary navigation 
[X] My changes are accessible (at minimum WCAG 2.0 Level AA)
[X] My changes are responsive and appear as expected on mobile and desktop views.
[X] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
##. Backend
Note: The following Taxonomy Term has been added to the Taxonomy Primary Navigation
Name : No Menu
Machine-name : no-menu
Multdev - https://sns-nomenu-chug.pantheonsite.io/ - for testing …
> added condition for no-menu in PN

- src/components/shared/links.js
- src/styles/links.module.css
Show two or 3 links as full width if in a 9 column section
Show two or 3 links as full width if in a 9 column section
List all significant changes to the Drupal site (e.g. new fields, content types, modules, etc). If adding new fields, try to include help text to ensure users understand how to use the fields.
View the following URLs
- Page with links in 9 column section: …
> Link widget - Show two or 3 links as full width if in a 9 column section

- config/sites/ugconthub.js
- gatsby-config.js
- package-lock.json
- package.json
- src/components/shared/button.js
- src/components/shared/callToAction.js
Remove the now-obsolete `gatsby-plugin-google-analytics` and update "Call to Action" code to be compatible with Google Tag Manager instead
- Convert custom event code in `callToAction.js`
- Convert custom event code in `button.js`
- Remove `gatsby-plugin-google-analytics` from `gatsby-config.js`
- Delete unneeded Google Analytics tracking ID from `ugconthub.js` config file
- Uninstall `gatsby-plugin-google-analytics`
- Run `prettier` on changed component files to clean up formatting (normally the "hide whitespace" option takes care of this on a PR, but for some reason it's not working on this one. As a workaround, go to https://app.semanticdiff.com/ and paste this URL - https://github.com/ccswbs/gus/pull/247/files - to exclude the `prettier` changes)
N/A
- Go to [Google Tag …
> Remove obsolete gatsby-plugin-google-analytics and update Call to Action code

- gatsby-node.js
- src/components/shared/accordion.js
Add new field `Accordion Description` for optional intro/explanation of Accordion items
- Add `Accordion Description` field to `accordion.js`
- Add `Accordion Description` field to schema in `gatsby-node.js`
- Remove `FieldAccordionBlockText` from schema and use `BodyField` instead (since they're identical aside from name)
[ x ] My changes are accessible (at minimum WCAG 2.0 Level AA)
[ x ] My changes are responsive and appear as expected on mobile and desktop views.
[ x ] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
- Add new long text field `Accordion Description` to Accordion widget
Multidev URL: …
> Add Accordion Description field

- src/components/shared/headerMenu.js
Currently if a page has a menu and that menu is empty, the header will not render on the page. So I've added a check to see if the menu is empty and still render a header, as if there was no menu.
- Modified check for empty menu to emit header in headerMenu.js
N/A
1. Go to a page with an empty menu (ex. https://66fec34bfe8a2d00085da7f8--preview-ugconthub.netlify.app/ridgetown/agriculture-diploma/) and see that the header does …
> Render header when menu is empty

- gatsby-node.js
Currently, our code does not create redirects in cases where the destination URL is archived, deleted, or affiliated with an external URL.
The logic is now changed to:
- loop through the redirects data rather than the aliases data
- create ALL redirects in the redirects table, including external URLs. The only exception is if the destination path is not an external URL and does not exist in the aliases table (e.g., if page was archived or deleted).
- keep the existing fix that stops redirects from being created if they point to themselves or if the only difference is case (e.g., uppercase, lowercase, camelCase)
In other words:
- If the redirect exist in the Redirects data:
-  If the sourcePath is affiliated with an archived page, the redirect **is** created (e.g., /maplewoods to …
> Create all redirects (not just alias-affiliated redirects)

- src/templates/program-page.js
I updated the links on the program page template for the buttons "View Admission Requirements", "Book a Tour" and "Request more Info".
View Admission Requirements takes you to: https://www.uoguelph.ca/admission/undergraduate/
Book a Tour takes you to: https://www.uoguelph.ca/admission/undergraduate/tours/
Request More Info takes you to: https://www.uoguelph.ca/admission/undergraduate/contact/
N/A
Check to see if:
1. View …
> Change the links for Admissions, Tours, Info in program template

- src/components/shared/blockWidget.js
If you add a block with a media text widget to a section, it does not behave as most media text widgets do. This appears to be because it does not pass the section region (if it exists) through to the media text widget.
- Pass the section region (if it exists) to the media text widget, otherwise pass an empty string
None
1. In the Preview deployment environment, review [PR deployment - Linda's Test …
> Pass region to media text in widget blocks

- src/components/shared/blockWidget.js
- src/components/shared/sectionWidgets.js
- src/components/shared/widget.js
Currently widget blocks are getting their region from the widget block data. However, for media & text widgets, we need to allow widget blocks to have a null region (in the case where they are not placed in a section).
Allow block widgets to have no section region selected
None
1. View [/test-page-linda-marciniak/](https://deploy-preview-256--preview-ugconthub.netlify.app/test-page-linda-marciniak/) to see if block appears as …
> Allow block widgets to have no section region selected

- src/templates/program-page.js
I just changed the text that appears before the Apply Now button from "Are you ready to Improve Life?" to "Get Future Ready" on the Program templates.
[N/A ] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
Check to see if this change appears on this specific program pages:
https://www.uoguelph.ca/programs/bachelor-of-applied-science/ 
https://www.uoguelph.ca/programs/bachelor-of-arts/
https://www.uoguelph.ca/programs/bachelor-of-arts-and-sciences/ …
> Change text before Apply Now button to Get Future Ready

- gatsby-ssr.js
- src/components/shared/hero.js
-  Add pre-loading for scripts and css in the header
- Eager loading for hero image
Updated gatsby-ssr.js to preload certain resources
Update hero component for eager loading
Check https://deploy-preview-267--preview-ugconthub.netlify.app/programs/bachelor-of-mathematics/
on Page Speed tool, vs existing live page. Should see some improvement in the overall times.
> Test Page perf

- src/components/shared/callToAction.js
- src/styles/global.css
- src/templates/program-page.js
Change the layout of the buttons (on the Bachelor of Commerce) from being 2 solid red buttons stacked to one outlined button on the left and one solid red button on the right. Also make "Learn More: all uppercase to match the "APPLY NOW" button.
List all significant changes to Gatsby code:
program-page.js, added code below:
btnClass = {index === (callToActionData.length - 1) ? 'btn-primary':'btn-outline-primary'}
callToAction.js, added line below:
let className = classNames(btnClass,'btn fs-1 me-4 p-4 w-100');
Check if the Apply Now button change to an outlined button:
https://deploy-preview-274--ugconthub.netlify.app/programs/bachelor-of-commerce/
> add outline for 1 of 2 buttons

- .netlify/edge-functions/block-bots.js
- netlify.toml
Trying method for block bots using Netlify edge function
https://ethanmarcotte.com/wrote/blockin-bots/ 
https://www.jeremiak.com/blog/block-bots-netlify-edge-functions/
It checks to see if the user agent is part of a list of bots and serves a 401 error if it finds the user agent on the list.
None
1. Check [deploy logs](https://app.netlify.com/sites/ugconthub/deploys/6785893c9a6d2b0008 …
> Add block-bots

- netlify.toml
Add trailing slash for lighthouse test urls to fix redirect that occurs from no-slash to trailing slash URLs.
None
None
1. Confirm this issue does not show up on lighthouse report:
> Add trailing slash for lighthouse test urls

- gatsby-node.js
Once the _Queue for Delete_ multidev is merged, we do not want content with that moderation state to be built. This PR updates the GraphQL filters to exclude all content with a moderation state other than Published or Draft.
- Update `allNodePage` and `allNodeProgram` queries in `gatsby-node.js`
URL: https://mm-qdelete-chug.pantheonsite.io/
See the [Queue for Delete workflow Multidev Merge Request](https://teams.microsoft.com/l/message/19:f2ae5b00dc95407d8902b0e04ff98ec1@thread.tacv2/1737650602575?tenantId=be62a12b-2cad-49a1-a5fa-85f4f3156a7d&groupId=cde949b1-e9d8-483b-8d20-e9b8fd9e493d&parentMessageId=1737650602575&teamName=Content%20Hub%20Team&channelName=Multidev%20Merge%20Requests&createdTime=1737650602575) for more details
Verify the [Content Hub Inventory …
> Update GraphQL filter to include published and draft content only

- gatsby-config.js
Prevent spotlight content from being processed by the build in order to prevent [this error on the Preview site](https://app.netlify.com/sites/preview-ugconthub/deploys/67aa6b847f740f0008c013aa):
- Update `gatsby-config.js` to filter spotlight content
N/A
- Go to https://api.devugconthub.uoguelph.dev/
- Delete some spotlight nodes
- Go to https://app.netlify.com/sites/dev-ugconthub/deploys and verify the build completes successfully
> Exclude Spotlight content type

- src/components/shared/sectionWidgets.js
- src/styles/global.css
- Media & text widgets inside a primary section are no longer appearing properly after last week's changes.
- Also the margin-top 0 style that was added last week is causing issues in some cases.
- Roll back row removal and margin-top 0 on media text widget 
- Roll back row removal and margin-top 0 on media text widget
None
1. View /housing/apply/ - https://deploy-preview-297--ugconthub.netlify.app/housing/apply/
2. View …
> Roll back row removal and margin-top 0 on media text widget

- src/styles/stats.css
Fix bug described in https://dev.azure.com/uoguelph/CCS/_sprints/taskboard/WDS%20Team/CCS/Sprint%202025.4?workitem=86314 where stat item text is black in mobile view (only affects Program content type)
- Update `stats.css` to remove obsolete program stat styles
N/A
- Go to https://deploy-preview-299--ugconthub.netlify.app/testprogram/
- Shrink window or use Mobile view via Browser inspector
- Verify text on stat items remains white against the red and black backgrounds
> Remove obsolete program stat styles

- src/components/shared/mediaText.js
Fix spacing for media-text widgets with no wrapper
Note: This particular example has had artificial whitespace (<br />) to try and fix the issue at the top, but then folks have to keep adding whitespace. This fix makes it so we handle the spacing in the styles. In the below example, I removed the artificial whitespace so you can see what it would look like.
Before:
After:
Fix spacing for media-text widgets with no wrapper
None …
> Fix spacing for media-text widgets with no wrapper

- src/components/shared/button.js
Add Drupal uuid as html id for buttons rendered via the buttons section widget.
This is to make it easier to track button click events in GA4
N/A
1. Go to any page with a buttons section ex. https://deploy-preview-316--ugconthub.netlify.app/choose-u-of-guelph/
2. Use Web Inspector on the buttons to check the ID of the buttons is set to a uuid
> Add unique ID to buttons

- src/styles/links.module.css
- src/styles/stats.css
- Fixes the size of the focus element for links widget (when it's a link instead of a grid box)
Before:
After:
- Fixes colour contrast when folks use links inside a .uog-card element
- Fixes the size of the focus element for links widget (when it's a link instead of a grid box)
- Fixes colour contrast when folks use links inside a .uog-card element
None
For link focus, use:
- https://mmafe-dev.netlify.app/widget-examples/
- …
> Fix focus element for links widget and colour contrast on legacy class
