ccswbs/gus

- package-lock.json
- src/pages/programs.js
- src/styles/programsList.css
- src/styles/stats.css
To create a page to display all the programs 
FRONTED (Gatsby): https://gusprogramlist.gatsbyjs.io/programs/
- programs.js - creates a page that has the programs listed in alphabetical order. Using cards linking back to the program page. 
- programsList.css - css for the programs list page
BACKEND (Drupal): live
- no changes
TESTING: 
The page https://gusprogramlist.gatsbyjs.io/programs/ should display all the program pages that are published - in alphabetical order.
> Programlist

- src/components/shared/breadcrumbs.js
Test to see if this resolves Gatsby Cloud build errors
Add extra null checks to `breadcrumbs.js`
Add extra null checks to `breadcrumbs.js`
> Add extra null checks

- src/components/shared/breadcrumbs.js
Brief description of the proposed changes
List all significant changes to the Drupal site (e.g. new fields, content types, modules, etc)
Insert steps. Include URLs of Gatsby Cloud test site and Drupal multidev.
> Remove conditional on homeCrumbURL

- package-lock.json
- package.json
- src/components/shared/breadcrumbs.js
Use in case idea of installing gatsby-plugin-catch-links and adding exclusion does not work.
> Remove home link and gatsby-plugin-catch-links

- gatsby-node.js
- src/components/shared/statisticWidget.js
Brief description of the proposed changes
List all significant changes to the Drupal site (e.g. new fields, content types, modules, etc)
Insert steps. Include URLs of Gatsby Cloud test site and Drupal multidev.
> Use new field for statistic value

- src/data/block/economic-impact/community-impact-mealcare.yml
- src/data/block/economic-impact/human-impact-banky.yml
Update banky and meal care videos to use YouTube instead of vimeo
Update banky and meal care videos to use YouTube instead of vimeo
None
1. Compile the PR branch
2. Visit /grce/impact-report
3. Scroll down to the Mealcare section and click "Watch video"
4. Video should play
5. Scroll down to the Banky section and click "Watch video"
6. Video should play
> Update banky and mealcare videos

- azure-pipelines.yml
- azuredeploy.json
- Remove live variable from azuredeploy.json file
- Comment out azure-pipelines code while we are testing azure build pipelines
None
None
Confirm build runs properly on Gatsby Cloud after this change has been made
> Remove live trigger on azure pipeline

- pull_request_template.md
Update pull request template for Github
None
None
Review pull request template and determine if they are worth adding.
> Update pull request template for Github

- pull_request_template.md
Update PR template with documentation link
None
None
- Review the wording of the Github PR template
> Update PR template with documentation link

- src/pages/404.js
Remove unnecessary tags, use className and avoid skipping headings
Remove unnecessary tags, use className and avoid skipping headings
None
- Check 404 page
- Ensure there are no skipped headings
- Ensure h2 is not red
- Remove unnecessary surrounding p tags
- Ensure no console warnings related to class instead of className
> Remove unnecessary tags, classes and avoid skipping headings

- src/components/shared/customFooter.js
Pipeline is broken due to null content in custom footer. Adding null checks to footer.
Adding null checks to footer.
None
Check that Netlify gus pipeline can complete for this pull request.
> Fix broken pipeline (Add null checks to custom footers)

- src/components/shared/linkswidget.js
- src/components/shared/sectionWidgets.js
- src/components/shared/widget.js
Add null checks for link widget
Add null checks for link widget
None
Ensure Netlify build completes
> Add null checks for link widget

- gatsby-config.js
Turn off fastbuilds
Turn off fastbuilds
None
See if build completes.
> Turn off fastbuilds

- gatsby-config.js
- gatsby-node.js
Brief description of the proposed changes
Turned on fastbuilds in gatsby config
[X] My changes are accessible (at minimum WCAG 2.0 Level AA)
[N/A] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
Added Gatsby module and enabled the Fastbuilds portion
Test build and see if it quicker.
> turn on fast builds

- azure-pipelines.yml
Add evening builds until 11 pm
None
None
- Check timing and ensure 4 more hours have been added to the schedule
> Add evening builds until 11 pm

- src/components/shared/hero.js
- src/styles/global.css
Update hero image size
changed image query for new width and height
[ ] My changes are accessible (at minimum WCAG 2.0 Level AA)
[ ] My changes are responsive and appear as expected on mobile and desktop views.
Update the help text for banner image size
Insert steps. Include URLs of Netlify test site and Drupal multidev.
> Update hero.js for image size

- .gitignore
- package-lock.json
- package.json
- src/components/shared/hero.js
- src/styles/hero.css
- Fixes an issue with the hero image caption/page title getting cutoff on smaller displays.
- Apply dependabot maintenance fixes
- Style changes in hero.css
- Apply dependabot maintenance fixes
None
1. Review https://deploy-preview-202--ugconthub.netlify.app/ for issues
2. Go to any page with a banner image (ex. https://deploy-preview-202--ugconthub.netlify.app/international/events/) on a smaller display, ensure the page title …
> Release/1.0.0: Update page title responsiveness and maintenance fixes

- src/templates/program-page.js
Hide the Unibuddy content on the program pages.
[x ] My changes are accessible (at minimum WCAG 2.0 Level AA)
[x ] My changes are responsive and appear as expected on mobile and desktop views.
Open Bachelor of Applied Science(and other programs template pages) to verify the Unibuddy content on the program pages was hidden.
> work items #78036, Change to the Program page- Bachelor of Computing

- src/pages/index.js
Changed:
pub = pub
&
unpub = unpub
Now, new pages will show up on preview site again.
> Preview pages should now show up. (pubPages = unPubPages was incorrect)

- src/styles/links.module.css
Added responsiveness to the link widget if there are 3 or less items. May need to set a max-height to the image as image gets very large on large screens at 1 item.
links.module.css
- changed hardcode 4 frames to repeat for flexibility with 3 items or less
- may need to set a max-height for image in file as 1 item is quite large on the screen
##Testing
Page to view for testing is: https://deploy-preview-236--ugconthub.netlify.app/admissions-0/.
> Update links.module.css to be responsive

- src/components/shared/pageTabs.js
Add null check for tab content
Add null check for tab content
None
1. Check that build completes
2. Check https://deploy-preview-258--preview-ugconthub.netlify.app/clone-master-engineering-meng-working-page/
> Add null check for tab content

- agents.json
Brief description of the proposed changes
[ ] My changes are accessible (at minimum WCAG 2.0 Level AA)
[ ] My changes are responsive and appear as expected on mobile and desktop views.
List all significant changes to the Drupal site (e.g. new fields, content types, modules, etc). If adding new fields, try to include help text to ensure users understand how to use the fields.
Insert steps. Include URLs of Netlify test site and Drupal multidev.
> Remove AdsBot-Google from blocked agents

- agents.json
- netlify/edge-functions/bots.ts
Block null user-agents
Block null user-agents
None
1. In a terminal, run `curl -H "User-Agent:" https://mmafe-dev.netlify.app`
2. Visit https://app.netlify.com/sites/mmafe-dev/logs/edge-functions 
3. Filter by the bot function and you should see `blocking null agent`
> Block null user-agents

- agents.json
- netlify.toml
Update Lighthouse configuration and add agents to blocker
None
None
1. View Lighthouse reports on the build and see if additional reports are generated. If you click the one lighthouse score, it should open a detailed view:
3. Confirm Netlify edge blocker still working as expected
> Update Lighthouse configuration and add agents to blocker

- src/templates/program-page.js
Update call to action on program template
Update call to action on program template
None
- Check a program page and confirm heading is updated: /programs/bachelor-of-arts
> Update call to action on program template

- src/templates/program-page.js
Training site broke because a null check was missing on the program overview. Re-added the null check.
- Added null check for program.overview
None
1. Check if the training site finishes building https://app.netlify.com/sites/trainingugconthub/deploys/67bdd7d49933aa92694f3ae5
> Add null check for program overview

- package-lock.json
- package.json
- Remove gatsby-source-wordpress
- Add #304 
- Add #309 
- Add #311 
- Package updates
None
1. Confirm everything is working
> Add dependabot releases and remove gatsby-source-wordpress
